name = "claim-check"
main = "src/index.ts"
compatibility_date = "2026-10-06"
workers_dev = true

[vars]
CANONICAL_ORIGIN = "https://claim-check.ohmygraph.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "claim-check"
database_id = "1eb00d45-556e-4b08-b662-4c7ffac36f19"
migrations_dir = "migrations"

[triggers]
crons = ["17 3 * * *"]
